import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/page";

import AppProvider from "./appProvider";
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "BikeInfo360",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body className={`${rubik.variable} antialiased`}>
        <AppProvider>
          <div className="flex tracking-tight flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            <Navbar />
            {children}
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
